config/routes.rb
Rails.application.routes.draw do
  root 'currencies#index'

  get 'currencies/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  def index
    @filters = {
      base:   params[:base]   || 'BRL',
      target: params[:target] || 'USD'
    }
    rates = Currencies::Index.call(@filters).response
    set_data(rates['rates'])
  end

  private

  def set_data(rates)
    @series     = []
    @categories = []
    rates.each do |rate|
      @series     << rate[1].map{|k,v| "#{v}".to_f }
      @categories << rate[0]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def currencies
    ['BRL','MXN','USD','EUR']
  end
end

app/views/currencies/index.html.erb
<div class="row justify-content-center mb-5">
  <div class="col-4 text-center">
    <h3>Currency Rates</h3>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-4 text-center">
    <%= form_tag currencies_index_path, :method => :get do %>
      <div class="form-row justify-content-center">
        <div class="form-group col-6">
          <label>Base Currency </label>
          <%= select_tag :base, options_for_select(currencies, @filters[:base]), class: 'form-control' %>
        </div>

        <div class="form-group col-6">
          <label>Target Currency </label>
          <%= select_tag :target, options_for_select(currencies, @filters[:target]), class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= submit_tag "Search", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-10 text-center">
    <div id="container" style="width:100%; height:400px;"></div>
  </div>
</div>

<script>
  var data = <%= raw( @series.flatten.to_json) %>
  var categories = <%= raw( @categories.flatten.sort.to_json) %>
  var name = <%= raw( @filters[:target].to_json) %>
  var myChart = Highcharts.chart('container', {
    title: {
      text: 'Last Working Week'
    },
    xAxis: {
      categories: categories
    },
    yAxis: {
      title: {
          text: '<%= "#{@filters[:base]} Rate" %>'
      }
    },
    series: [{name: name, data: data}]
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Currency Rates</title>
    <%= favicon_link_tag('currency.png') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script src="https://code.highcharts.com/highcharts.src.js"></script>

  </head>

  <body>
  <div class="container-fluid mt-5">
    <%= yield %>
  </div>

  </body>
</html>